services:
  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  container_name: frontend
  #  ports:
  #    - 5000:5000

  pyprep:
    build:
      context: ./pyprep-process
      dockerfile: Dockerfile
    container_name: pyprep
    volumes:
     - ./results:/results
    depends_on: 
      - backend
    networks:
      - mind-cloud

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - db
      - pulsar
    networks:
      - mind-cloud

  pulsar:
    image: apachepulsar/pulsar:4.0.5
    ports:
      - 6650:6650
    command: bin/pulsar standalone
    networks:
      - mind-cloud

  db:
    container_name: eeg-db
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=eeg-db
      - POSTGRES_DB=eeg-db
      - POSTGRES_USER=eeg_user
      - POSTGRES_PASSWORD=password
    volumes: 
      - db_data:/var/lib/postgresql/data
    networks:
      - mind-cloud

  adminer:
    image: adminer:5.3.0
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_SERVER=eeg-db
    networks:
      - mind-cloud
  
volumes:
  db_data:
    driver: local

networks:
  mind-cloud:
    driver: bridge