services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5000:5000

  #preprocessor:
  #  build:
  #    context: ./preprocessor
  #    dockerfile: Dockerfile
  #  container_name: preprocessor
  #  volumes:
  #   - ./data_files:/data_files
  #  depends_on: 
  #    - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8005:8005
    depends_on:
      - db

  pulsar:
    image: apachepulsar/pulsar:4.0.5
    ports:
      - 6650:6650
    command: bin/pulsar standalone

  db:
    container_name: eeg-db
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=eeg-db
      - POSTGRES_DB=eeg-db
      - POSTGRES_USER=eeg_user
      - POSTGRES_PASSWORD=password
    volumes: 
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:5.3.0
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_SERVER=eeg-db
  
volumes:
  db_data:
    driver: local